<table border="0" cellpadding="0" cellspacing="0" width="98%" height="39" <%=table_pos_style1%>>
<tr height="39">
<td width="240"><img border="0" src="./images/header_left.gif" width="240" height="39"></td>
<td width="100%" background="./images/header_center.gif"><font size="5" color="#FFFFFF" ><p align="center"style="top: 4; z-index: 0; position: relative"></p></font>
<td align="right" width="26"><img border="0" src="./images/header_right.gif" width="26" height="39"></td>
</tr>
</table>
<%if ie_ind then%><br><%end if%>
<table border="0" cellpadding="0" cellspacing="0" width="98%" <%=table_pos_style2%>>
<tr height="20">
<td colspan=3 bgcolor="#66CCFF">
<table border="0" cellpadding="0" cellspacing="0" width="98%" bordercolorlight="#000000">
  <tr>
    <td width="100"><a href="default.asp"><img border="0" src="./images/home_button.gif" height="20" width="100" onmouseover="header_image(this,'home_button_mouseover')" onmouseout="header_image(this,'home_button')" onclick="header_image(this,'home_button')"></a></td>
    <td width="100"><img border="0" src="./images/about_button.gif" height="20" width="100" onmouseover="header_image(this,'about_button_mouseover')" onmouseout="header_image(this,'about_button')"></td>
    <td width="100"><a href="request_form.asp"><img border="0" src="./images/downloads_button.gif" height="20" width="100" onmouseover="header_image(this,'downloads_button_mouseover')" onmouseout="header_image(this,'downloads_button')"></a></td>
    <td width="100"><img border="0" src="./images/links_button.gif" height="20" width="100" onmouseover="header_image(this,'links_button_mouseover')" onmouseout="header_image(this,'links_button')"></td>
    <td width="100%" background="button_rest.gif"><p><font color="#66CCFF">'</font></p></td>
  </tr>
</table>
</td>
<tr>
</table>

